name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.9.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Build prepare
        run: pnpm build:prepare

      - name: Test
        run: pnpm test
